language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
virtualenv:
  system_site_packages: true
# command to run tests
#script:
#  - pytest